server:
  port: 8081
  servlet:
    context-path: "/blog-api"
spring:
  application:
    name: BLOG-API

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_timesheet
    username: root
    password: Believeingod01!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# JWt properties
app.jwt-secret: JWTSecretKey
app.jwt-expiration-milliseconds: 604800000 #7 expiration days

logging:
  level:
    org:
      springframework:
        security: debug


